# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This will set up a `python_requirement_library` target `pants-plugins:pantsbuild.pants`. It will
# read the `pants_version` from `pants.toml`.
pants_requirement()
