# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# These will set up `python_requirement_library` targets `pants-plugins:pantsbuild.pants` and
# `pants-plugins:pantsbuild.pants.testutil`. They will read the `pants_version` from `pants.toml`.

pants_requirement(name="pants", dist="pantsbuild.pants")
pants_requirement(name="testutil", dist="pantsbuild.pants.testutil")
